# Generated by Django 5.2.13 on 2026-06-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationPage', '0009_donation_payment_type_donation_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='donor',
            name='id_country',
            field=models.CharField(blank=True, help_text='Country that issued the identification (natural persons)', max_length=60, verbose_name='country of issue'),
        ),
        migrations.AddField(
            model_name='donor',
            name='id_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='identification / registration number'),
        ),
        migrations.AddField(
            model_name='donor',
            name='id_type',
            field=models.CharField(blank=True, choices=[('sa_id', 'South African ID'), ('passport', 'Passport'), ('registration', 'Company Registration Number'), ('trust_number', "Master's Reference / Trust Number"), ('other', 'Other')], max_length=20, verbose_name='identification type'),
        ),
        migrations.AddField(
            model_name='donor',
            name='income_tax_ref',
            field=models.CharField(blank=True, max_length=60, verbose_name='income tax reference number'),
        ),
        migrations.AddField(
            model_name='donor',
            name='nature_of_donor',
            field=models.CharField(blank=True, choices=[('natural_person', 'Natural Person'), ('company', 'Company'), ('close_corporation', 'Close Corporation'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='trading_name',
            field=models.CharField(blank=True, help_text='Trading name of the donor, if different from the registered name', max_length=200),
        ),
        migrations.CreateModel(
            name='S18ACertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('trading_name', models.CharField(blank=True, help_text='Trading name of the donor, if different from the registered name', max_length=200)),
                ('nature_of_donor', models.CharField(blank=True, choices=[('natural_person', 'Natural Person'), ('company', 'Company'), ('close_corporation', 'Close Corporation'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=20)),
                ('id_type', models.CharField(blank=True, choices=[('sa_id', 'South African ID'), ('passport', 'Passport'), ('registration', 'Company Registration Number'), ('trust_number', "Master's Reference / Trust Number"), ('other', 'Other')], max_length=20, verbose_name='identification type')),
                ('id_country', models.CharField(blank=True, max_length=60, verbose_name='country of issue')),
                ('id_number', models.CharField(blank=True, max_length=60, verbose_name='identification / registration number')),
                ('income_tax_ref', models.CharField(blank=True, max_length=60, verbose_name='income tax reference number')),
                ('contact_number', models.CharField(blank=True, max_length=60)),
                ('contact_email', models.EmailField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('tax_year', models.PositiveIntegerField(blank=True, help_text='Year of assessment ending end-February, e.g. 2026', null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nature_of_donation', models.CharField(default='Cash (via EFT)', help_text="Nature of the donation, e.g. 'Cash (via EFT)'", max_length=200)),
                ('date_of_donation_text', models.CharField(blank=True, help_text="Free text, e.g. 'R100 Monthly, March 2025 through February 2026'", max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('emailed', 'Emailed to donor')], default='pending', max_length=20)),
                ('receipt_number', models.PositiveIntegerField(blank=True, help_text='Allocated automatically on approval', null=True, unique=True)),
                ('requested_by_donor', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('emailed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('signatory_name', models.CharField(default='Nathan Geffen', max_length=100)),
                ('signatory_title', models.CharField(default='Director', max_length=100)),
                ('signatory_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donations', models.ManyToManyField(blank=True, related_name='certificates', to='donationPage.donation')),
                ('donor', models.ForeignKey(blank=True, help_text='Leave blank for a fully custom donor / organisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='donationPage.donor')),
            ],
            options={
                'verbose_name': 'S18A certificate',
                'ordering': ['-requested_at'],
            },
        ),
    ]
