# Generated by Django 5.2.13 on 2026-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationPage', '0010_donor_address_donor_contact_number_donor_id_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='s18acertificate',
            name='pdf_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='s18a/', verbose_name='issued PDF'),
        ),
    ]
