# Generated by Django 5.2.13 on 2026-08-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationPage', '0011_s18acertificate_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Required by SARS for a natural person who has no South African ID number', null=True),
        ),
        migrations.AddField(
            model_name='s18acertificate',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Required by SARS for a natural person who has no South African ID number', null=True),
        ),
        migrations.AddField(
            model_name='s18acertificate',
            name='first_names',
            field=models.CharField(blank=True, help_text='CSV export only. Leave blank to split the donor name.', max_length=200),
        ),
        migrations.AddField(
            model_name='s18acertificate',
            name='surname',
            field=models.CharField(blank=True, help_text='CSV export only. Leave blank to split the donor name.', max_length=200),
        ),
    ]
